# This file was generated by GoReleaser. DO NOT EDIT.
cask "boundary" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "a7257c77bd2545f7e2b6b87222ed507d2b947faad15688c10dd68c9f39369963"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_darwin_arm64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
    on_intel do
      sha256 "873b94acf3517cc08f8065765e9a23f3d3010e38530dce97f7a6849ea759e770"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_darwin_amd64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
  end
  on_linux do
    on_arm do
      sha256 "e2ced8debd1650343ef747ef4f7ed80ebbafe433930cb013f81be37ce698bfaa"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_linux_arm64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
    on_intel do
      sha256 "4dd2a9646ed6c183d9f072e55990ee6f3e826babc1e3194aa817c16e27771901"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_linux_amd64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
  end

  name "boundary"
  desc "Pre-execution action boundary for routed AI-agent tool calls"
  homepage "https://github.com/Fulcrum-Governance/Fulcrum-Boundary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boundary"

  # No zap stanza required

  caveats <<~EOS
    This cask installs the static (CGO_ENABLED=0) build. Its Postgres
    AST classifier is unavailable: every routed SQL statement classifies as
    UNKNOWN and the Postgres guard denies it fail-closed. For the full SQL
    classifier, download a `_cgo` release archive or build from source with
    Go 1.25+ and a C toolchain. See docs/INSTALL.md.
  EOS
end
