# This file was generated by GoReleaser. DO NOT EDIT.
cask "boundary" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "1775ce5622b61c668a180e999159e3ee4944db91bda0d0233b8a010733135cb9"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_darwin_amd64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
    on_arm do
      sha256 "fd4512b2d3f724ee4e38ac1cbad809b7e9c46f65331867046f25f6a3b406d8a5"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_darwin_arm64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e90e565006778509b9564ebcdc2e49ac59119c1fc30afa9c77c2736f69a61bdc"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_linux_amd64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
    on_arm do
      sha256 "8d976845764bd21f78b41be1a043f1b3f0317e2d3c15c5fe7510ef35f2b83824"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_linux_arm64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
  end

  name "boundary"
  desc "Pre-execution action boundary for routed AI-agent tool calls"
  homepage "https://github.com/Fulcrum-Governance/Fulcrum-Boundary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boundary"

  # No zap stanza required

  caveats <<~EOS
    This cask installs the static (CGO_ENABLED=0) build. Its Postgres
    AST classifier is unavailable: every routed SQL statement classifies as
    UNKNOWN and the Postgres guard denies it fail-closed. For the full SQL
    classifier, download a `_cgo` release archive or build from source with
    Go 1.25+ and a C toolchain. See docs/INSTALL.md.
  EOS
end
