# This file was generated by GoReleaser. DO NOT EDIT.
cask "boundary" do
  version "0.13.1"

  on_macos do
    on_arm do
      sha256 "bfc5603bd3080a6b1b0365ebad2f22c87e5b384cab817c644c02a84b0235218f"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_darwin_arm64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
    on_intel do
      sha256 "4d819deecd4a1fcd57531baa0727563e5a4df57067fdcaab57a7ec0ef6d27839"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_darwin_amd64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
  end
  on_linux do
    on_arm do
      sha256 "f2b9222011e51d8d33c29f965d7278d16e9e4ff9bdc437faaa7c889fd60a6639"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_linux_arm64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
    on_intel do
      sha256 "6182e05d825ab930fee817a16ece1ea012e2b838bbd13ac976eda728e6411972"
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v#{version}/boundary_#{version}_linux_amd64_static-nocgo.tar.gz",
        verified: "github.com/Fulcrum-Governance/Fulcrum-Boundary/"
    end
  end

  name "boundary"
  desc "Pre-execution action boundary for routed AI-agent tool calls"
  homepage "https://github.com/Fulcrum-Governance/Fulcrum-Boundary"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boundary"

  # No zap stanza required

  caveats <<~EOS
    This cask installs the static (CGO_ENABLED=0) build. Its Postgres
    AST classifier is unavailable: every routed SQL statement classifies as
    UNKNOWN and the Postgres guard denies it fail-closed. For the full SQL
    classifier, download a `_cgo` release archive or build from source with
    Go 1.25+ and a C toolchain. See docs/INSTALL.md.
  EOS
end
