# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boundary < Formula
  desc "Pre-execution action boundary for routed AI-agent tool calls"
  homepage "https://github.com/Fulcrum-Governance/Fulcrum-Boundary"
  version "0.10.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.10.1/boundary_0.10.1_darwin_amd64_static-nocgo.tar.gz"
      sha256 "bbeda621aea3fa6bb1c1b7ce25b66fa4a933ead8c1d01b0a509659083f80b6b2"

      define_method(:install) do
        bin.install "boundary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.10.1/boundary_0.10.1_darwin_arm64_static-nocgo.tar.gz"
      sha256 "b302f00acfba5c787829a5a61503e090eba4abb43572569684981dd28c13bf95"

      define_method(:install) do
        bin.install "boundary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.10.1/boundary_0.10.1_linux_amd64_static-nocgo.tar.gz"
      sha256 "a0cfa110b8e38df8366b6e4609769fa741378d78f4adcb6d73c9166a10e7fb67"
      define_method(:install) do
        bin.install "boundary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.10.1/boundary_0.10.1_linux_arm64_static-nocgo.tar.gz"
      sha256 "ceef6e617ef5557f19b5d1b3722e06b8c4099b6f9b30191adbdca9eb11bff6b5"
      define_method(:install) do
        bin.install "boundary"
      end
    end
  end

  def caveats
    <<~EOS
      This formula installs the static (CGO_ENABLED=0) build. Its Postgres
      AST classifier is unavailable: every routed SQL statement classifies as
      UNKNOWN and the Postgres guard denies it fail-closed. For the full SQL
      classifier, download a `_cgo` release archive or build from source with
      Go 1.25+ and a C toolchain. See docs/INSTALL.md.
    EOS
  end

  test do
    system "#{bin}/boundary", "version"
  end
end
