# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boundary < Formula
  desc "Pre-execution action boundary for routed AI-agent tool calls"
  homepage "https://github.com/Fulcrum-Governance/Fulcrum-Boundary"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.11.0/boundary_0.11.0_darwin_amd64_static-nocgo.tar.gz"
      sha256 "b90384148382807397b8e7a5ea151f6bc3da902bd3964470387d3b6139d81aa4"

      define_method(:install) do
        bin.install "boundary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.11.0/boundary_0.11.0_darwin_arm64_static-nocgo.tar.gz"
      sha256 "7b87532d10f90fb02ca0ae94bc37bcaf071ee2af4b263d3cb7bd848a12ff71f1"

      define_method(:install) do
        bin.install "boundary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.11.0/boundary_0.11.0_linux_amd64_static-nocgo.tar.gz"
      sha256 "9944af6b2012a81e9441e28c28221e966d69f3b8ccea22c8d64c017824914d25"
      define_method(:install) do
        bin.install "boundary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fulcrum-Governance/Fulcrum-Boundary/releases/download/v0.11.0/boundary_0.11.0_linux_arm64_static-nocgo.tar.gz"
      sha256 "cfc6b1aaeed891db63f8e6bd5b0e5688e43b8df2d5b12bce72a40660af15c05c"
      define_method(:install) do
        bin.install "boundary"
      end
    end
  end

  def caveats
    <<~EOS
      This formula installs the static (CGO_ENABLED=0) build. Its Postgres
      AST classifier is unavailable: every routed SQL statement classifies as
      UNKNOWN and the Postgres guard denies it fail-closed. For the full SQL
      classifier, download a `_cgo` release archive or build from source with
      Go 1.25+ and a C toolchain. See docs/INSTALL.md.
    EOS
  end

  test do
    system "#{bin}/boundary", "version"
  end
end
